name: Download from S3 and Upload to JFrog

on:
workflow_call:

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (if needed)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   # Set in GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Set in GitHub Secrets
          aws-region: 'us-east-1'  # Replace with your AWS region

      # Step 3: Download all folders from the S3 bucket
      - name: Download all folders from S3
        run: |
          mkdir -p s3-downloads  # Create a local directory to store the S3 files
          aws s3 sync s3://test-bucket-jfrog s3-downloads/  # Sync the S3 bucket to the local directory
          ls s3-downloads/  # List the downloaded files for verification

      # Step 4: Setup JFrog CLI
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        with:
          jfrog-url: ${{ secrets.JF_URL }}  # JFrog Artifactory URL
          jfrog-deploy-repo: 'my-repo-local'  # Replace with your JFrog repository name
          oidc-provider-name: 'my-oidc-provider'
          oidc-audience: 'my-audience'

      # Step 5: Upload to JFrog, preserving folder structure
      - name: Upload folders to JFrog
        run: |
          jf rt upload "s3-downloads/(*)" "my-repo-local/{1}/" --flat=false  # Upload with folder structure
