name: S3 to JFrog Workflow

on:
  workflow_call:

jobs:
  s3-to-jfrog:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Use the composite action to download from S3 and upload to JFrog
      - name: Run composite action to sync S3 with JFrog
        uses: your-username/composite-s3-jfrog-action/.github/actions/s3-to-jfrog@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
          s3-bucket: 'test-bucket-jfrog'
          jfrog-url: ${{ secrets.JF_URL }}
          jfrog-repo: 'my-repo-local'
