# .github/workflows/download_artifact.yml
name: Reusable Workflow for Downloading Artifact and Uploading to JFrog

on:
  workflow_call:

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Install yq (YAML query tool)
        run: sudo apt-get install -y yq

      - name: Download Latest Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.workflow }}-*  # Use wildcard to download the latest artifact uploaded with the workflow name

      - name: Extract GitHub repository name (ignoring organization)
        id: extract_repo_name
        run: |
          GITHUB_REPO_NAME=$(basename "${{ github.repository }}")
          echo "repo_name=$GITHUB_REPO_NAME" >> $GITHUB_ENV

- name: Check JFrog Repository Access
  run: |
    # Set up environment variables
    GITHUB_REPO="$repo_name"
    JFROG_REPO="${{ inputs.JFROG_REPO }}"  # This should come from workflow inputs or env variables

    # Export the environment variables so that they are available to yq
    export GITHUB_REPO
    export JFROG_REPO

    # Check if the GitHub repository exists in the repo-mapping.yml file
    REPO_EXISTS=$(yq eval '.repository_mapping[] | select(.github_repo == env.GITHUB_REPO)' ./called-workflow-repo/config/jfrog/repo-mapping.yml)

    if [ -z "$REPO_EXISTS" ]; then
      echo "Error: The GitHub repository $GITHUB_REPO is not found in the repository mapping."
      exit 1
    fi

    # Now check if the JFrog repository is allowed
    ALLOWED_REPO=$(yq eval '.repository_mapping[] | select(.github_repo == env.GITHUB_REPO) | .JFROG_ALLOWED_DESTINATION_REPOS[] | select(. == env.JFROG_REPO)' ./called-workflow-repo/config/jfrog/repo-mapping.yml)

    if [ -z "$ALLOWED_REPO" ]; then
      echo "Error: The GitHub repository $GITHUB_REPO is not allowed to deploy to JFrog repository $JFROG_REPO."
      exit 1
    else
      echo "Success: The GitHub repository $GITHUB_REPO is allowed to deploy to JFrog repository $JFROG_REPO."
    fi


      - name: Upload to JFrog
        run: |
          JFROG_URL="your-jfrog-url"
          ARTIFACT_PATH=$(ls -1 *.zip)
          jfrog rt upload $ARTIFACT_PATH $JFROG_REPO/$ARTIFACT_PATH
