name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Upload Artifact
  job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Artifact for Job 1
      run: |
        mkdir -p artifact_job1
        echo "This is the artifact from Job 1" > artifact_job1/job1.txt

    - name: Upload Artifact for Job 1
      uses: actions/upload-artifact@v4
      with:
        name: job_1_artifact
        path: artifact_job1/job1.txt  # Path to the file being uploaded

  # Job 2: Upload Another Artifact
  job_2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate Artifact for Job 2
      run: |
        mkdir -p artifact_job2
        echo "This is the artifact from Job 2" > artifact_job2/job2.txt

    - name: Upload Artifact for Job 2
      uses: actions/upload-artifact@v4
      with:
        name: job_2_artifact
        path: artifact_job2/job2.txt  # Path to the file being uploaded

  # Job 3: Download All Artifacts and Process Them
  download_and_process:
    runs-on: ubuntu-latest
    needs: [job_1, job_2]  # Ensure this job waits for Job 1 and Job 2 to finish
    steps:
    - name: make artifacts
      run: mkdir all_artifacts
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./all_artifacts
    - name: Debug
      run: ls -la all_artifacts
